---
# Example Playbook: VLAN configuration using the [ucs] hosts group
- hosts: ucs1
  connection: local
  gather_facts: false
  
  tasks:
    - name: UCS Connection Information vars
      fail:
        msg: 'Please define the following variables: ucs_hostname, ucs_username and ucs_password.'
      when: ucs_hostname is not defined or ucs_username is not defined or ucs_password is not defined
      vars:
       login_info: &login_info
         hostname: "{{ucs_hostname}}"
         username: "{{ucs_username}}"
         password: "{{ucs_password}}"
         
    - name: Import CSV
      read_csv:
        path: excel-csv.csv
        register: excel
        delegate_to: localhost

    - name: Configure VLAN
      ucs_vlans:
      loop: '{{excel.list}}'
      vars:
        <<: *login_info
        state: present
        name: '{{item.name}}'
        id: '{{item.vlan}}'
        native: 'no'
    
    - name: Configure MAC address pool
      ucs_mac_pool:
        <<: *login_info
        name: mac-ansible
        org_dn: org-root
        first_addr: 00:25:B5:00:66:00
        last_addr: 00:25:B5:00:67:F3
        order: sequential
  
    - name: Configure IPv4 address pool
      ucs_ip_pool:
        <<: *login_info
        name: ippool-ansible
        org_dn: org-root
        first_addr: 192.168.10.1
        last_addr: 192.168.10.20
        subnet_mask: 255.255.255.128
        default_gw: 192.168.10.2
        primary_dns: 64.104.76.247
 
    - name: Configure NTP server
      ucs_ntp_server:
        <<: *login_info
        ntp_server: 10.10.10.10
        description: Internal NTP Server by IP address
        state: present
        
    - name: Configure UUID address pool
      ucs_uuid_pool:
        <<: *login_info
        name: UUID-ansible
        order: sequential
        first_uuid: 0000-000000000001
        last_uuid: 0000-000000000078
        
    - name: Configure VSAN
      ucs_vsans:
        <<: *login_info
        name: vsan110
        vsan_id: '1100'
        vlan_id: '1100'
        
    - name: Configure WWNN policy
      ucs_wwn_pool:
        <<: *login_info
        name: WWNN-ansible
        purpose: node
        first_addr: 20:00:00:25:B5:48:00:00
        last_addr: 20:00:00:25:B5:48:00:0F
